In [ ]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as splt
import seaborn 
import os, sys

In [ ]:
from google.colab import  files
files.upload()

Saving PatientDetails_Classification.csv to PatientDetails_Classification.csv

{'PatientDetails_Classification.csv': b'Patient Name,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,TARGET\r\nA,6,148,72,35,0,33.6,0.627,50,1\r\nB,1,85,66,29,0,26.6,0.351,31,0\r\nC,8,183,64,0,0,23.3,0.672,32,1\r\nD,1,89,66,23,94,28.1,0.167,21,0\r\nE,0,137,40,35,168,43.1,2.288,33,1\r\nF,5,116,74,0,0,25.6,0.201,30,0\r\nG,3,78,50,32,88,31,0.248,26,1\r\nH,10,115,0,0,0,35.3,0.134,29,0\r\nI,2,197,70,45,543,30.5,0.158,53,1\r\nJ,8,125,96,0,0,0,0.232,54,1\r\nK,4,110,92,0,0,37.6,0.191,30,1\r\nL,10,168,74,0,0,38,0.537,34,1\r\nM,10,139,80,0,0,27.1,1.441,57,0\r\nN,1,189,60,23,846,30.1,0.398,59,1\r\nO,5,166,72,19,175,25.8,0.587,51,1\r\nP,7,100,0,0,0,30,0.484,32,1\r\nQ,0,118,84,47,230,45.8,0.551,31,1\r\nR,7,107,74,0,0,29.6,0.254,31,1\r\nS,1,103,30,38,83,43.3,0.183,33,1\r\nT,1,115,70,30,96,34.6,0.529,32,1\r\nU,3,126,88,41,235,39.3,0.704,27,0\r\nV,8,99,84,0,0,35.4,0.388,50,0\r\nW,7,196,90,0,0,39.8,0.451,41,1\r\nX,9,119,80,35,0,29,0.263,29,1\r\nY,11,143,94,33,146,36.6,0.254,51,1\r\nZ,10,125,70,26,115,31.1,0.205,41,1\r\n'}

In [ ]:
df=pd.read_csv("PatientDetails_Classification.csv")

In [ ]:
df

,Patient Name,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,TARGET
0,A,6,148,72,35,0,33.6,0.627,50,1
1,B,1,85,66,29,0,26.6,0.351,31,0
2,C,8,183,64,0,0,23.3,0.672,32,1
3,D,1,89,66,23,94,28.1,0.167,21,0
4,E,0,137,40,35,168,43.1,2.288,33,1
5,F,5,116,74,0,0,25.6,0.201,30,0
6,G,3,78,50,32,88,31.0,0.248,26,1
7,H,10,115,0,0,0,35.3,0.134,29,0
8,I,2,197,70,45,543,30.5,0.158,53,1
9,J,8,125,96,0,0,0.0,0.232,54,1
10,K,4,110,92,0,0,37.6,0.191,30,1
11,L,10,168,74,0,0,38.0,0.537,34,1
12,M,10,139,80,0,0,27.1,1.441,57,0
13,N,1,189,60,23,846,30.1,0.398,59,1
14,O,5,166,72,19,175,25.8,0.587,51,1
15,P,7,100,0,0,0,30.0,0.484,32,1
16,Q,0,118,84,47,230,45.8,0.551,31,1
17,R,7,107,74,0,0,29.6,0.254,31,1
18,S,1,103,30,38,83,43.3,0.183,33,1
19,T,1,115,70,30,96,34.6,0.529,32,1
20,U,3,126,88,41,235,39.3,0.704,27,0
21,V,8,99,84,0,0,35.4,0.388,50,0
22,W,7,196,90,0,0,39.8,0.451,41,1
23,X,9,119,80,35,0,29.0,0.263,29,1
24,Y,11,143,94,33,146,36.6,0.254,51,1
25,Z,10,125,70,26,115,31.1,0.205,41,1

In [ ]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,TARGET
count,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000
mean,5.307692,130.615385,66.923077,18.884615,108.423077,31.930769,0.480692,38.000000,0.730769
std,3.674444,34.289447,25.083737,17.562066,193.816444,8.830709,0.458998,11.121151,0.452344
min,0.000000,78.000000,0.000000,0.000000,0.000000,0.000000,0.134000,21.000000,0.000000
25%,1.250000,107.750000,64.500000,0.000000,0.000000,28.325000,0.211750,30.250000,0.250000
50%,5.500000,122.000000,72.000000,23.000000,0.000000,31.050000,0.369500,32.500000,1.000000
75%,8.000000,146.750000,83.000000,34.500000,138.250000,37.350000,0.547500,50.000000,1.000000
max,11.000000,197.000000,96.000000,47.000000,846.000000,45.800000,2.288000,59.000000,1.000000

In [ ]:
x=df.iloc[:,:-1]

In [ ]:
x

,Patient Name,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,A,6,148,72,35,0,33.6,0.627,50
1,B,1,85,66,29,0,26.6,0.351,31
2,C,8,183,64,0,0,23.3,0.672,32
3,D,1,89,66,23,94,28.1,0.167,21
4,E,0,137,40,35,168,43.1,2.288,33
5,F,5,116,74,0,0,25.6,0.201,30
6,G,3,78,50,32,88,31.0,0.248,26
7,H,10,115,0,0,0,35.3,0.134,29
8,I,2,197,70,45,543,30.5,0.158,53
9,J,8,125,96,0,0,0.0,0.232,54
10,K,4,110,92,0,0,37.6,0.191,30
11,L,10,168,74,0,0,38.0,0.537,34
12,M,10,139,80,0,0,27.1,1.441,57
13,N,1,189,60,23,846,30.1,0.398,59
14,O,5,166,72,19,175,25.8,0.587,51
15,P,7,100,0,0,0,30.0,0.484,32
16,Q,0,118,84,47,230,45.8,0.551,31
17,R,7,107,74,0,0,29.6,0.254,31
18,S,1,103,30,38,83,43.3,0.183,33
19,T,1,115,70,30,96,34.6,0.529,32
20,U,3,126,88,41,235,39.3,0.704,27
21,V,8,99,84,0,0,35.4,0.388,50
22,W,7,196,90,0,0,39.8,0.451,41
23,X,9,119,80,35,0,29.0,0.263,29
24,Y,11,143,94,33,146,36.6,0.254,51
25,Z,10,125,70,26,115,31.1,0.205,41

In [ ]:
y=df.iloc[:,9]

In [ ]:
y

0     1
1     0
2     1
3     0
4     1
5     0
6     1
7     0
8     1
9     1
10    1
11    1
12    0
13    1
14    1
15    1
16    1
17    1
18    1
19    1
20    0
21    0
22    1
23    1
24    1
25    1
Name: TARGET, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=.3,random_state=1)

In [ ]:
xtrain

,Patient Name,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
4,E,0,137,40,35,168,43.1,2.288,33
2,C,8,183,64,0,0,23.3,0.672,32
21,V,8,99,84,0,0,35.4,0.388,50
6,G,3,78,50,32,88,31.0,0.248,26
14,O,5,166,72,19,175,25.8,0.587,51
7,H,10,115,0,0,0,35.3,0.134,29
23,X,9,119,80,35,0,29.0,0.263,29
1,B,1,85,66,29,0,26.6,0.351,31
16,Q,0,118,84,47,230,45.8,0.551,31
0,A,6,148,72,35,0,33.6,0.627,50
15,P,7,100,0,0,0,30.0,0.484,32
25,Z,10,125,70,26,115,31.1,0.205,41
24,Y,11,143,94,33,146,36.6,0.254,51
9,J,8,125,96,0,0,0.0,0.232,54
8,I,2,197,70,45,543,30.5,0.158,53
12,M,10,139,80,0,0,27.1,1.441,57
11,L,10,168,74,0,0,38.0,0.537,34
5,F,5,116,74,0,0,25.6,0.201,30

In [ ]:
xtest

,Patient Name,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
18,S,1,103,30,38,83,43.3,0.183,33
13,N,1,189,60,23,846,30.1,0.398,59
17,R,7,107,74,0,0,29.6,0.254,31
3,D,1,89,66,23,94,28.1,0.167,21
22,W,7,196,90,0,0,39.8,0.451,41
10,K,4,110,92,0,0,37.6,0.191,30
19,T,1,115,70,30,96,34.6,0.529,32
20,U,3,126,88,41,235,39.3,0.704,27

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
KNN = KNeighborsClassifier()

In [ ]:
KNN.fit(xtrain,ytrain)

ValueError: ignored

In [ ]:
df.shape

(26, 10)

In [ ]:
df["Patient Name"].value_counts()

A    1
B    1
Y    1
X    1
W    1
V    1
U    1
T    1
S    1
R    1
Q    1
P    1
O    1
N    1
M    1
L    1
K    1
J    1
I    1
H    1
G    1
F    1
E    1
D    1
C    1
Z    1
Name: Patient Name, dtype: int64

In [ ]:
df.dtypes

Patient Name                 object
Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
TARGET                        int64
dtype: object

In [ ]:
df.replace({'Patient Name':{'A':1,'B':2,'C':3,'D':4,'E':5,'F':6,'G':7,'H':8,'I':9,'J':10,'K':11,'L':12,'M':13,'N':14,'O':15,'P':16,'Q':17,'R':18,'S':19,'T':20,'U':21,'V':22,'W':23,'X':24,'Y':25,'Z':26}},inplace=True)

In [ ]:
df["Patient Name"].value_counts()

1     1
2     1
25    1
24    1
23    1
22    1
21    1
20    1
19    1
18    1
17    1
16    1
15    1
14    1
13    1
12    1
11    1
10    1
9     1
8     1
7     1
6     1
5     1
4     1
3     1
26    1
Name: Patient Name, dtype: int64

In [ ]:
df

,Patient Name,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,TARGET
0,1,6,148,72,35,0,33.6,0.627,50,1
1,2,1,85,66,29,0,26.6,0.351,31,0
2,3,8,183,64,0,0,23.3,0.672,32,1
3,4,1,89,66,23,94,28.1,0.167,21,0
4,5,0,137,40,35,168,43.1,2.288,33,1
5,6,5,116,74,0,0,25.6,0.201,30,0
6,7,3,78,50,32,88,31.0,0.248,26,1
7,8,10,115,0,0,0,35.3,0.134,29,0
8,9,2,197,70,45,543,30.5,0.158,53,1
9,10,8,125,96,0,0,0.0,0.232,54,1
10,11,4,110,92,0,0,37.6,0.191,30,1
11,12,10,168,74,0,0,38.0,0.537,34,1
12,13,10,139,80,0,0,27.1,1.441,57,0
13,14,1,189,60,23,846,30.1,0.398,59,1
14,15,5,166,72,19,175,25.8,0.587,51,1
15,16,7,100,0,0,0,30.0,0.484,32,1
16,17,0,118,84,47,230,45.8,0.551,31,1
17,18,7,107,74,0,0,29.6,0.254,31,1
18,19,1,103,30,38,83,43.3,0.183,33,1
19,20,1,115,70,30,96,34.6,0.529,32,1
20,21,3,126,88,41,235,39.3,0.704,27,0
21,22,8,99,84,0,0,35.4,0.388,50,0
22,23,7,196,90,0,0,39.8,0.451,41,1
23,24,9,119,80,35,0,29.0,0.263,29,1
24,25,11,143,94,33,146,36.6,0.254,51,1
25,26,10,125,70,26,115,31.1,0.205,41,1

In [ ]:
x=df.iloc[:,:-1]

In [ ]:
x

,Patient Name,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,1,6,148,72,35,0,33.6,0.627,50
1,2,1,85,66,29,0,26.6,0.351,31
2,3,8,183,64,0,0,23.3,0.672,32
3,4,1,89,66,23,94,28.1,0.167,21
4,5,0,137,40,35,168,43.1,2.288,33
5,6,5,116,74,0,0,25.6,0.201,30
6,7,3,78,50,32,88,31.0,0.248,26
7,8,10,115,0,0,0,35.3,0.134,29
8,9,2,197,70,45,543,30.5,0.158,53
9,10,8,125,96,0,0,0.0,0.232,54
10,11,4,110,92,0,0,37.6,0.191,30
11,12,10,168,74,0,0,38.0,0.537,34
12,13,10,139,80,0,0,27.1,1.441,57
13,14,1,189,60,23,846,30.1,0.398,59
14,15,5,166,72,19,175,25.8,0.587,51
15,16,7,100,0,0,0,30.0,0.484,32
16,17,0,118,84,47,230,45.8,0.551,31
17,18,7,107,74,0,0,29.6,0.254,31
18,19,1,103,30,38,83,43.3,0.183,33
19,20,1,115,70,30,96,34.6,0.529,32
20,21,3,126,88,41,235,39.3,0.704,27
21,22,8,99,84,0,0,35.4,0.388,50
22,23,7,196,90,0,0,39.8,0.451,41
23,24,9,119,80,35,0,29.0,0.263,29
24,25,11,143,94,33,146,36.6,0.254,51
25,26,10,125,70,26,115,31.1,0.205,41

In [ ]:
y=df.iloc[:,9]

In [ ]:
y

0     1
1     0
2     1
3     0
4     1
5     0
6     1
7     0
8     1
9     1
10    1
11    1
12    0
13    1
14    1
15    1
16    1
17    1
18    1
19    1
20    0
21    0
22    1
23    1
24    1
25    1
Name: TARGET, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=.3,random_state=1)

In [ ]:
xtrain

,Patient Name,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
4,5,0,137,40,35,168,43.1,2.288,33
2,3,8,183,64,0,0,23.3,0.672,32
21,22,8,99,84,0,0,35.4,0.388,50
6,7,3,78,50,32,88,31.0,0.248,26
14,15,5,166,72,19,175,25.8,0.587,51
7,8,10,115,0,0,0,35.3,0.134,29
23,24,9,119,80,35,0,29.0,0.263,29
1,2,1,85,66,29,0,26.6,0.351,31
16,17,0,118,84,47,230,45.8,0.551,31
0,1,6,148,72,35,0,33.6,0.627,50
15,16,7,100,0,0,0,30.0,0.484,32
25,26,10,125,70,26,115,31.1,0.205,41
24,25,11,143,94,33,146,36.6,0.254,51
9,10,8,125,96,0,0,0.0,0.232,54
8,9,2,197,70,45,543,30.5,0.158,53
12,13,10,139,80,0,0,27.1,1.441,57
11,12,10,168,74,0,0,38.0,0.537,34
5,6,5,116,74,0,0,25.6,0.201,30

In [ ]:
ytrain

4     1
2     1
21    0
6     1
14    1
7     0
23    1
1     0
16    1
0     1
15    1
25    1
24    1
9     1
8     1
12    0
11    1
5     0
Name: TARGET, dtype: int64

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
KNN =  KNeighborsClassifier()

In [ ]:
KNN.fit(x,y)

KNeighborsClassifier()

In [59]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
y_pred=KNN.predict(xtest)
print("KNN Naive Bayes")
print("Accuracy")
print(accuracy_score(ytest, y_pred))
print("Confusion matrix")
conf_matrix=confusion_matrix(ytest,y_pred)
print(conf_matrix)
print(classification_report(ytest, y_pred))

KNN Naive Bayes
Accuracy
0.75
Confusion matrix
[[0 2]
 [0 6]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.75      1.00      0.86         6

    accuracy                           0.75         8
   macro avg       0.38      0.50      0.43         8
weighted avg       0.56      0.75      0.64         8

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))